services:
  php-fpm:
    build: .
    restart: always
    volumes:
      - ../:${REMOTE_PATH}
    extra_hosts:
      - ${VIRTUAL_HOST}:${PROXY_NETWORK_GATEWAY}
    networks:
      - nginx-proxy-network
      - backend
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ../:${REMOTE_PATH}
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - nginx-proxy-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - backend

networks:
  nginx-proxy-network:
    external: true
  backend:
